// AUTO-GENERATED by scripts/codex/update-models.ts — do not edit manually
// Source: https://raw.githubusercontent.com/openai/codex/main/codex-rs/core/models.json

import type { Model } from './agents.ts';

/** Codex models fetched from the official codex repository, filtered to visibility=list */
export const CODEX_MODELS: Model[] = [
  {
    id: 'gpt-5.3-codex',
    name: 'gpt-5.3-codex',
    description: 'Latest frontier agentic coding model.',
  },
  {
    id: 'gpt-5.2-codex',
    name: 'gpt-5.2-codex',
    description: 'Frontier agentic coding model.',
  },
  {
    id: 'gpt-5.1-codex-max',
    name: 'gpt-5.1-codex-max',
    description: 'Codex-optimized flagship for deep and fast reasoning.',
  },
  {
    id: 'gpt-5.2',
    name: 'gpt-5.2',
    description:
      'Latest frontier model with improvements across knowledge, reasoning and coding',
  },
  {
    id: 'gpt-5.1-codex-mini',
    name: 'gpt-5.1-codex-mini',
    description: 'Optimized for codex. Cheaper, faster, but less capable.',
  },
];
