// ============================================================================
// Configuration Service - Read/write .hermes/config.yml file
// ============================================================================

import { mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { YAML } from 'bun';

const CONFIG_DIR = '.hermes';
const CONFIG_FILENAME = 'config.yml';
const CONFIG_PATH = join(CONFIG_DIR, CONFIG_FILENAME);

export type AgentType = 'claude' | 'opencode';

export interface HermesConfig {
  // Tiger service ID to use as the default parent for database forks
  // null = explicitly "none" (skip DB fork by default)
  // undefined = not set
  tigerServiceId?: string | null;

  // Default agent to use (claude or opencode)
  agent?: AgentType;

  // Default model to use for the selected agent
  model?: string;
}

/**
 * Read the .hermes/config.yml file from the current directory
 * Returns undefined if the file doesn't exist
 */
export async function readConfig(): Promise<HermesConfig | undefined> {
  const file = Bun.file(CONFIG_PATH);
  if (!(await file.exists())) {
    return undefined;
  }

  const content = await file.text();
  const parsed = YAML.parse(content);

  // Handle empty file or invalid YAML
  if (!parsed || typeof parsed !== 'object') {
    return {};
  }

  return parsed as HermesConfig;
}

/**
 * Write the .hermes/config.yml file to the current directory
 * Creates the .hermes directory if it doesn't exist
 */
export async function writeConfig(config: HermesConfig): Promise<void> {
  // Ensure .hermes directory exists
  await mkdir(CONFIG_DIR, { recursive: true });
  await Bun.write(
    CONFIG_PATH,
    `# Hermes configuration
# Generated by 'hermes init'
# https://github.com/timescale/hermes
---
${YAML.stringify(config, null, 2)}
`,
  );
}
