#!/usr/bin/env bun

// Fetches the official codex models list from GitHub and generates a TypeScript
// file with the visible models sorted by priority.
//
// Usage:
//   ./bun scripts/codex/update-models.ts
//
// The generated file is committed to git so builds don't require network access.

const MODELS_URL =
  'https://raw.githubusercontent.com/openai/codex/main/codex-rs/core/models.json';
const OUTPUT_PATH = 'src/services/codexModels.generated.ts';

interface CodexModelEntry {
  slug: string;
  display_name?: string;
  description?: string;
  visibility?: string;
  priority?: number;
}

interface CodexModelsJson {
  models: CodexModelEntry[];
}

async function main() {
  const response = await fetch(MODELS_URL);
  if (!response.ok) {
    throw new Error(
      `Failed to fetch models.json: ${response.status} ${response.statusText}`,
    );
  }

  const data = (await response.json()) as CodexModelsJson;

  // Filter to visible models and sort by priority (ascending)
  const visible = data.models
    .filter((m) => m.visibility === 'list')
    .sort((a, b) => (a.priority ?? 999) - (b.priority ?? 999));

  if (visible.length === 0) {
    throw new Error('No visible models found in models.json');
  }

  const modelEntries = visible
    .map((m) => {
      const id = m.slug;
      const name = m.display_name ?? m.slug;
      const desc = (m.description ?? '').replace(/'/g, "\\'");
      return `  { id: '${id}', name: '${name}', description: '${desc}' },`;
    })
    .join('\n');

  const content = `// AUTO-GENERATED by scripts/codex/update-models.ts — do not edit manually
// Source: ${MODELS_URL}

import type { Model } from './agents.ts';

/** Codex models fetched from the official codex repository, filtered to visibility=list */
export const CODEX_MODELS: Model[] = [
${modelEntries}
];
`;

  await Bun.write(OUTPUT_PATH, content);
  console.log(
    `Wrote ${visible.length} models to ${OUTPUT_PATH}:`,
    visible.map((m) => m.slug),
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
